config/routes.rb
  Rails.application.routes.draw do

  root 'main#index'
  ActiveAdmin.routes(self)

  get 'categories/import', to: 'categories#import'
  get 'categories/import_city', to: 'categories#import_city'
  get 'categories/:id', to: 'categories#index', as: 'categories'

  get 'contact', to: 'pages#contact', as: 'contact'
  get 'rules',   to: 'pages#rules',   as: 'rules'
  get 'about',   to: 'pages#about',   as: 'about'
  get 'dogovor', to: 'pages#dogovor', as: 'dogovor'
  get 'news',    to: 'pages#news',    as: 'news'

  get 'profile(/:id)', to: 'users#index', as: 'profile'
  get 'users/login'
  get 'users/reg'
  get 'users/new_password'
  get 'profile/requests(/:type/(:id))', to: 'users#requests', as: 'profile_requests'
  get 'profile/bids(/:type/(:id))',       to: 'users#bids', as: 'profile_bids'
  get 'profile/managed(/:type(:id/))',     to: 'users#managed', as: 'profile_managed'

  patch 'requests/addMinimumPrice/:id', to: 'requests#add_minimum_price', as: 'addMinimumPrice'
  get   'requests/searchModal', to: 'requests#search_modal', as: 'search_modal'
  get   'requests/cat:id', to: 'requests#index', as: 'requests_category'
  get   'requests/archive', to: 'requests#archive', as: 'requests_archive'
  get   'requests/await', to: 'requests#await', as: 'requests_await'
  get   'requests/refused/:id', to: 'requests#refused', as: 'request_refused'
  get   'requests/payed/:id', to: 'requests#payed', as: 'request_payed'
  get   'requests/close/:id', to: 'requests#close', as: 'request_close'
  get   'requests/take/:id', to: 'requests#take', as: 'request_take'

  get  'invoice/:id', to: 'invoice#show', as: 'invoice'
  get  'bill/:id', to: 'invoice#bill', as: 'bill'

  resources :contacts,
    :controller => 'contacts',
    :only       => [:create]

  post '/documents/:temp_key', to: 'documents#create', as: 'documents_create'
  get '/documents/:id', to: 'documents#show', as: 'documents_show'
  delete '/documents/:id', to: 'documents#delete', as: 'documents_delete'
  resources :requests
  resources :bids, :only => [:create]

  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations', passwords: 'passwords'}
  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/views/partials/_footer.html.slim
footer
  .container
    .col-12
      a.logo(href="/")
        = image_tag "white-logo.png"
    .navbar.col-12
      ul
        li
          =link_to "Новости", news_url
        li
          =link_to "О нас", about_url
        li
          =link_to 'Заявки', requests_path
        li
          =link_to "Архив", requests_archive_path
        li
          =link_to "Правила", rules_url
        li
          =link_to "Контакты", contact_url
    .copyr.col-12
      p  © CENASPROSA. Все права защищены. 2015 г.

app/views/partials/_header.html.slim
header
  .container
    .col-4.header-col
      a.logo(href="/")
        = image_tag "black-logo.png"

    .col-4.header-col
      .search-box
        =search_form_for Request.ransack(params[:q]), :html => {:class => "search"}  do |f|
          =f.text_field :name_cont, :placeholder => "поиск по наименованию товара"
          input type="submit" value="" src="assets/search-icon.png"
        .more-search
          =link_to search_modal_path, class: 'modal-trigger', data: {target: 'exp-search'}
            | расширеный поиск
    .col-4.header-col
      .login-box

        -unless user_signed_in?
          =link_to users_login_path, class: 'modal-trigger', data: {target: 'login'}
            button.login-btn Вход
          =link_to users_reg_path, class: 'modal-trigger', data: {target: 'reg'}
            button.registr-btn Регистрация
        -else
          -case current_user.role
            -when "provider"
              =link_to profile_path
                button.small-button.registr-btn Кабинет поставщика
            -when "costumer"
              =link_to profile_path
                button.small-button.registr-btn Кабинет заказчика
              -if user_signed_in? && current_user.status == 'active'
                =link_to new_request_path, class: 'modal-trigger', data: {target: 'add-bid'}
                  button.small-button.add-btn Добавить заявку
            -when "manager"
              =link_to profile_path
                button.small-button.registr-btn Кабинет менеджера
          =link_to destroy_user_session_path, :method => :delete
            button.small-button.login-btn Выход



    .col-12.header-col
      a.logo(href="/")
        = image_tag "black-logo.png"
  .navbar
    ul
      li
        =link_to "Новости", news_url
      li
        =link_to "О нас", about_url
      -if can?(:take, Request)
        li
          =link_to "Ожидают проверки", requests_await_path
      li
        =link_to "Заявки", requests_path
      li
        =link_to "Архив", requests_archive_path

      li
        =link_to "Правила", rules_url
      li
        =link_to "Контакты", contact_url