config/routes.rb
  Rails.application.routes.draw do

  root 'main#index'
  ActiveAdmin.routes(self)

  get 'categories/import', to: 'categories#import'
  get 'categories/import_city', to: 'categories#import_city'
  get 'categories/:id', to: 'categories#index', as: 'categories'

  get 'contact', to: 'pages#contact', as: 'contact'
  get 'rules',   to: 'pages#rules',   as: 'rules'
  get 'about',   to: 'pages#about',   as: 'about'
  get 'dogovor', to: 'pages#dogovor', as: 'dogovor'
  get 'news',    to: 'pages#news',    as: 'news'

  get 'profile(/:id)', to: 'users#index', as: 'profile'
  get 'users/login'
  get 'users/reg'
  get 'users/new_password'
  get 'profile/requests(/:type/(:id))', to: 'users#requests', as: 'profile_requests'
  get 'profile/bids(/:type/(:id))',       to: 'users#bids', as: 'profile_bids'
  get 'profile/managed(/:type(:id/))',     to: 'users#managed', as: 'profile_managed'

  patch 'requests/addMinimumPrice/:id', to: 'requests#add_minimum_price', as: 'addMinimumPrice'
  get   'requests/searchModal', to: 'requests#search_modal', as: 'search_modal'
  get   'requests/cat:id', to: 'requests#index', as: 'requests_category'
  get   'requests/archive', to: 'requests#archive', as: 'requests_archive'
  get   'requests/await', to: 'requests#await', as: 'requests_await'
  get   'requests/refused/:id', to: 'requests#refused', as: 'request_refused'
  get   'requests/payed/:id', to: 'requests#payed', as: 'request_payed'
  get   'requests/close/:id', to: 'requests#close', as: 'request_close'
  get   'requests/take/:id', to: 'requests#take', as: 'request_take'

  get  'invoice/:id', to: 'invoice#show', as: 'invoice'
  get  'bill/:id', to: 'invoice#bill', as: 'bill'

  resources :contacts,
    :controller => 'contacts',
    :only       => [:create]

  post '/documents/:temp_key', to: 'documents#create', as: 'documents_create'
  get '/documents/:id', to: 'documents#show', as: 'documents_show'
  delete '/documents/:id', to: 'documents#delete', as: 'documents_delete'
  resources :requests
  resources :bids, :only => [:create]

  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations', passwords: 'passwords'}
  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :default_values
  has_many :bid
  has_many :requests, :dependent => :destroy
  after_create :send_email
  after_update :send_aprove_email

  REGISTRATION_ROLES_LABELS = ['Вы поставщик','Вы заказчик']
  REGISTRATION_ROLES =        ['provider','costumer']

  ROLES =        ['Поставщик','Заказчик','Менеджер']
  ROLES_LABELS = ['provider','costumer','manager']

  STATUS_TYPES   = [ "disable", "active"]
  STATUS_LABELS  = [ "Неактивен", "Активен"]


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:username]

  attr_accessor :password_confirmation, :terms

  validates :role, :company_name, :company_phone, :ur_adress, :fis_adress, :contact_phone, :fio_contact, :remember_word,:inn, :kpp, :post_index, :presence => true

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :role,   :inclusion => REGISTRATION_ROLES, :on => :create
  validates :role,   :inclusion => ROLES_LABELS, :on => :update

  validates_inclusion_of :terms,  :in => ["1"], :message => "Вы должны согласится с условиями использования", :on => :create

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email_company, :email_contact, presence: true, format: { with: VALID_EMAIL_REGEX }

  validates :inn, :kpp, :post_index, :numericality => {:only_integer => true}, :allow_blank => true
  validates :password,:password_confirmation, :presence => true, :on => :create

  def default_values
    self.status ||= User::STATUS_TYPES[0]
    # for device password recovery
    self.email  = self.email_contact
  end

  def send_aprove_email
    if (self.status_changed? && self.status == "active")
      MainMailer.aprove_user(self).deliver_later
    end
  end
  def send_email
    MainMailer.new_user(self).deliver_later
  end

  def get_status
    i = STATUS_TYPES.index(self.status)
    STATUS_LABELS[i]
  end

  def self.roles_options
    return [
        [User::ROLES[0],User::ROLES_LABELS[0]],
        [User::ROLES[1],User::ROLES_LABELS[1]],
        [User::ROLES[2],User::ROLES_LABELS[2]]
    ]
  end

  def self.status_options
    return [
        [User::STATUS_LABELS[0],User::STATUS_TYPES[0]],
        [User::STATUS_LABELS[1],User::STATUS_TYPES[1]]
    ]
  end


  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @user = get_user
  end

  def show
    puts 'TESt'
  end

  def requests
    @user = get_user
    if params[:type] && params[:type] == "archived"
      @requests = Request.archived.where({:user_id =>@user.id})
    else
      @requests = Request.active.where({:user_id =>@user.id})
    end
  end

  def bids
    @user = get_user
    if params[:type] && params[:type] == "archived"
      @bids     = Bid.unscoped.where(:user_id => @user.id).joins(:request)
      .where("status != ? OR closing_time < ?",Request::STATUS_TYPES[1],Time.current).select(:request_id).distinct
    else
      @bids     = Bid.unscoped.where(:user_id => @user.id).joins(:request)
      .where("status  = ? AND closing_time > ?",Request::STATUS_TYPES[1],Time.current).select(:request_id).distinct
    end
  end

  def managed
    @user = get_user
    if params[:type] && params[:type] == "archived"
      @requests = Request.archived.where({:manager_id =>@user.id})
    else
      @requests = Request.active.where({:manager_id =>@user.id})
    end
    render 'requests'
  end


  def search
    render 'modals/_search', :layout => false
  end

  def login
    render 'modals/_login', :layout => false
  end

  def reg
    render 'modals/_reg', :layout => false
  end

  def new_password
    render 'modals/_new_password', :layout => false
  end

  private
    def get_user
      if !params[:id]
        current_user
      else
        User.find(params[:id])
      end
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_login.html.slim
=semantic_form_for User.new, url: { action: "create", :controller=>"sessions"}, remote: true, :html => {:id => 'login_user',:class => "exp-search-form",role: :form, 'data-model' => 'user', :'data-type' => 'json'} do |f|
  .col-modal
    =f.input :username, label: "Логин для входа", :as => :string
    =f.input :password,      label: "Пароль", :as => :password
    = link_to "Забыли пароль?", users_new_password_path, :class => "login-link modal-trigger",data: {target: 'new-password'}

  .exp-search-btn-block
    =f.button 'Войти', :class =>'modal-btn'

app/views/users/_new_password.html.slim
=semantic_form_for User.new, url: '/users/password', remote: true, :html => {:id => 'new_password_user',:class => "exp-search-form",role: :form, 'data-model' => 'user', :'data-type' => 'json'} do |f|
  .col-modal
    =f.input :email_contact, label: "Email контактного лица", :as => :string
    =f.input :remember_word, label: "Проверочное слово", :as => :string
  .exp-search-btn-block
    =f.button 'Восстановить', :class =>'modal-btn'

app/views/users/_reg.html.slim
=semantic_form_for User.new, url: registration_path(:user), remote: true, :html => {:class => "exp-search-form",role: :form, 'data-model' => 'user',:'data-type' => 'json'} do |f|
  .col-modal.payment-block.provider-block
    .payment-block-item.tax-block-item
      =f.input :role, :as => :radio, :collection => {User::REGISTRATION_ROLES_LABELS[0] => User::REGISTRATION_ROLES[0]},:label => false
    .payment-block-item.tax-block-item
      =f.input :role, :as => :radio, :collection => {User::REGISTRATION_ROLES_LABELS[1] => User::REGISTRATION_ROLES[1]},:label => false
  .col-modal
    =f.input :company_name,  label: "Название организации"
    =f.input :company_phone, label: "Контактный телефон организации", :as => :string
    =f.input :email_company, label: "Email организации", :as => :string
    =f.input :ur_adress,     label: "Юридический адрес организации", :as => :string
    =f.input :fis_adress,    label: "Фактический адрес организации", :as => :string
    =f.input :inn,           label: "ИНН Организации", :as => :string
    =f.input :kpp,           label: "КПП Организации", :as => :string
    =f.input :post_index,    label: "Почтовый индекс", :as => :string
  .col-modal
    =f.input :fio_contact,   label: "ФИО контактного лица", :as => :string
    =f.input :contact_phone, label: "Телефон контактного лица", :as => :string
    =f.input :email_contact, label: "Email контактного лица", :as => :string
    =f.input :username,      label: "Логин для входа", :as => :string
    =f.input :password,      label: "Пароль", :as => :password
    =f.input :password_confirmation, label: "Подтвердить пароль", :as => :password
    =f.input :remember_word,       label: "Проверочное слово", :as => :string
    =link_to "Пользовательское соглашение", dogovor_path, :target => "_blank"
    =f.input :terms,          label: "Я принимаю условия соглашения", :as => :boolean
  .exp-search-btn-block
    =f.button 'Зарегестрироваться', :class =>'modal-btn'

app/views/users/bids.html.slim
== render 'partials/header'
  =@user.company_name
.section.profile
  =render 'users/tabs/provider'
  .content-block
    .container
      .col-12
        h1 =@user.company_name
    -@bids.each do |bid|
      ==render bid.request


== render 'partials/footer'

app/views/users/create.html.slim
=@test

app/views/users/index.html.slim
== render 'partials/header'
  =@user.company_name
.section.profile
  -case @user.role
    -when "provider"
      =render 'users/tabs/provider'
    -when "costumer"
      =render 'users/tabs/costumer'
    -when "manager"
      =render 'users/tabs/manager'

  .content-block
    .container
      .col-12
        h1 =@user.company_name
      .col-4.request-item.request-item-timings

        p.open-time
          span Телефон организации:&nbsp <br>
          span =@user.company_phone
        p.options
          span Email организации:&nbsp <br>
          span =@user.email_company

      .col-4.request-item.request-solo-item-options
        p.delivery-date
          span Юридический адрес организации:&nbsp <br>
          span =@user.ur_adress
        p.delivery-date
          span Фактический адрес организации:&nbsp <br>
          span =@user.fis_adress
        p.pay-var.request-solo-item-option
          span Инн организации:&nbsp <br>
          span =@user.inn
      .col-4.request-item.request-item-ship-options
        p.delivery-date
          span ФИО контактного лица:&nbsp <br>
          span =@user.fio_contact
        p.delivery-date
          span Тел. контактного лица:&nbsp <br>
          span =@user.contact_phone
        p.delivery-date
          span Email контактного лица:&nbsp <br>
          span =@user.email_contact
== render 'partials/footer'

app/views/users/requests.html.slim
== render 'partials/header'
  =@user.company_name
.section.profile
  -case @user.role
    -when "provider"
      =render 'users/tabs/provider'
    -when "costumer"
      =render 'users/tabs/costumer'
    -when "manager"
      =render 'users/tabs/manager'
  .content-block
    .container
      .col-12
        h1 =@user.company_name
    ==render @requests
== render 'partials/footer'