config/routes.rb
  Rails.application.routes.draw do

  root 'main#index'
  ActiveAdmin.routes(self)

  get 'categories/import', to: 'categories#import'
  get 'categories/import_city', to: 'categories#import_city'
  get 'categories/:id', to: 'categories#index', as: 'categories'

  get 'contact', to: 'pages#contact', as: 'contact'
  get 'rules',   to: 'pages#rules',   as: 'rules'
  get 'about',   to: 'pages#about',   as: 'about'
  get 'dogovor', to: 'pages#dogovor', as: 'dogovor'
  get 'news',    to: 'pages#news',    as: 'news'

  get 'profile(/:id)', to: 'users#index', as: 'profile'
  get 'users/login'
  get 'users/reg'
  get 'users/new_password'
  get 'profile/requests(/:type/(:id))', to: 'users#requests', as: 'profile_requests'
  get 'profile/bids(/:type/(:id))',       to: 'users#bids', as: 'profile_bids'
  get 'profile/managed(/:type(:id/))',     to: 'users#managed', as: 'profile_managed'

  patch 'requests/addMinimumPrice/:id', to: 'requests#add_minimum_price', as: 'addMinimumPrice'
  get   'requests/searchModal', to: 'requests#search_modal', as: 'search_modal'
  get   'requests/cat:id', to: 'requests#index', as: 'requests_category'
  get   'requests/archive', to: 'requests#archive', as: 'requests_archive'
  get   'requests/await', to: 'requests#await', as: 'requests_await'
  get   'requests/refused/:id', to: 'requests#refused', as: 'request_refused'
  get   'requests/payed/:id', to: 'requests#payed', as: 'request_payed'
  get   'requests/close/:id', to: 'requests#close', as: 'request_close'
  get   'requests/take/:id', to: 'requests#take', as: 'request_take'

  get  'invoice/:id', to: 'invoice#show', as: 'invoice'
  get  'bill/:id', to: 'invoice#bill', as: 'bill'

  resources :contacts,
    :controller => 'contacts',
    :only       => [:create]

  post '/documents/:temp_key', to: 'documents#create', as: 'documents_create'
  get '/documents/:id', to: 'documents#show', as: 'documents_show'
  delete '/documents/:id', to: 'documents#delete', as: 'documents_delete'
  resources :requests
  resources :bids, :only => [:create]

  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations', passwords: 'passwords'}
  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  belongs_to :manager,:foreign_key => "manager_id", :class_name => "User"
  has_many :bids, dependent: :destroy
  has_many :documents, dependent: :destroy

  mount_uploader :file, DefaultUploader
  after_save :bind_documents

  validate :price_to_100

  default_scope { order(created_at: :desc) }
  scope :archived, -> {where("status  = ? OR status  = ?",STATUS_TYPES[3],STATUS_TYPES[4])}
  scope :active,   -> {where("status  = ?",STATUS_TYPES[1])}
  scope :await,    -> {where("status  = ? OR status  = ?",STATUS_TYPES[0],STATUS_TYPES[2])}


  PAYMENT_LABELS = [ "100%", "50%/50%", "Договорная"]
  PAYMENT_TYPES  = [ "100", "50", "contract"]

  STATUS_TYPES   = [ "disable", "active", "check_sended","refused", "payed"]
  STATUS_LABELS  = [ "Неактивная", "Активная", "Счет отправлен", "Отказ от оплаты", "Оплачено"]


  validates :name,:closing_time,:delivery_time,:section,:city,:payment_term, :presence => true

  validates :price, :numericality => {:only_integer => false, :allow_blank => true, :greater_than_or_equal_to => 10000, :message => "Минимальная сумма заявки не может быть меньше 10000р"}
  validates :price, :numericality => {:only_integer => false, :allow_blank => true, :less_than_or_equal_to => 1000000000, :message => "Максимальная сумма заявки не может быть больше 1000000000р"}

  validates_inclusion_of :delivery_term,:nds, in: [true, false]
  validates :payment_term, :inclusion => PAYMENT_TYPES
  validates :closing_time, date: { after: Proc.new  { Time.now + 8.hour }, message: 'Выберите более позднюю дату', allow_blank: true }, :on => :create
  validates :delivery_time, date: { after: Proc.new { Time.now + 3.hour }, message: 'Выберите более позднюю дату', allow_blank: true}, :on => :create

  ## Методы для человекапонятного вывода true:false соответствующих полей
  def get_nds
    self.nds ? "С НДС" : "Без НДС"
  end

  def get_delivery_term
    self.delivery_term ? "С доставкой" : "Без доставки"
  end

  def get_payment_term
    i = PAYMENT_TYPES.index(self.payment_term)
    PAYMENT_LABELS[i]
  end

  def get_status
    i = STATUS_TYPES.index(self.status)
    STATUS_LABELS[i]
  end

  ## Лейбл/значение для селектов методов оплаты
  def self.payment_term_options
    return [
        [Request::PAYMENT_LABELS[0],Request::PAYMENT_TYPES[0]],
        [Request::PAYMENT_LABELS[1],Request::PAYMENT_TYPES[1]],
        [Request::PAYMENT_LABELS[2],Request::PAYMENT_TYPES[2]]
    ]
  end

  def self.status_options
    return [
        [Request::STATUS_LABELS[0],Request::STATUS_TYPES[0]],
        [Request::STATUS_LABELS[1],Request::STATUS_TYPES[1]],
        [Request::STATUS_LABELS[2],Request::STATUS_TYPES[2]],
        [Request::STATUS_LABELS[3],Request::STATUS_TYPES[3]],
        [Request::STATUS_LABELS[4],Request::STATUS_TYPES[4]]
    ]
  end

  def price_to_100
    if !self.price.to_i.blank? and self.price.to_i % 100 > 0
      errors.add(:price, "Минимальный шаг цены 100 руб.")
    end
  end

  def bind_documents
    documents = Document.where(temp_key: self.temp_key).all
    documents.each do |document|
      document.request_id = self.id
      document.save
    end
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!, :only => :create
  load_and_authorize_resource

  def index
    if params[:id]
      @q = Request.active.where(:category_id => params[:id]).page(params[:page]).per(30).ransack(params[:q])
    else
      @q = Request.active.page(params[:page]).per(30).ransack(params[:q])
    end
    @requests = @q.result(distinct: true)
  end

  def archive
    @q = Request.archived.page(params[:page]).per(30).ransack(params[:q])
    @requests = @q.result(distinct: true)
    render 'index'
  end

  def await
    @q = Request.await.page(params[:page]).per(30).ransack(params[:q])
    @requests = @q.result(distinct: true)
    render 'index'
  end

  def show
    @request = Request.includes([{:bids => :user}, :documents]).find_by_id(params[:id])
  end

  def new
    o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
    @temp_key = (0...50).map { o[rand(o.length)] }.join
    render 'modals/_new_request', :layout => false
  end

  def search_modal
    render 'modals/_search', :layout => false
  end

  def edit
    o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
    @temp_key = (0...50).map { o[rand(o.length)] }.join
    render 'modals/_new_request', :layout => false
  end

  def create
    @request = Request.new(request_params)
    @request.user_id = current_user.id
    @request.status  = 'disable'
    @request.minimum_price = request_params['price']
    respond_to do |format|
      if @request.save
        format.js { render json: {responseText: "Ваша заявка успешно добавлена на портал Цена Спроса и ожидает подтверждения менеджера.", location: request_path(@request)}, status: :created }
        MainMailer.new_request(@request).deliver_later
      else
        format.js { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @request = Request.find(params[:id])
    update_params = request_params
    update_params['minimum_price'] = update_params['price']
    respond_to do |format|
      if @request.update_attributes(update_params)
        format.js { render json: {responseText: "Заявка успешно отредактирована", location: request_path(@request)}, status: :created }
      else
        format.js { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @request = Request.find(params[:id])
    MainMailer.decline_request(@request).deliver_later
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_path }
      format.json { head :no_content }
    end
  end

  def take
    @request = Request.find(params[:id])
    @request.update_attributes({:manager_id => current_user.id, :status => Request::STATUS_TYPES[1]})
    MainMailer.aprove_request(@request).deliver_later
    respond_to do |format|
      format.html { redirect_to request_path(@request) }
      format.json { head :no_content }
      format.js
    end
  end

  def refused
    @request = Request.find(params[:id])
    @request.update_attributes({:status => Request::STATUS_TYPES[3]})
    respond_to do |format|
      format.html { redirect_to request_path(@request) }
      format.json { head :no_content }
      format.js
    end
  end

  def payed
    @request = Request.find(params[:id])
    @request.update_attributes({:status => Request::STATUS_TYPES[4]})
    respond_to do |format|
      format.html { redirect_to request_path(@request) }
      format.json { head :no_content }
      format.js
    end
  end

  def close
    @request = Request.find(params[:id])
    @request.update_attributes({:status => Request::STATUS_TYPES[3]})
    respond_to do |format|
      format.html { redirect_to request_path(@request) }
      format.json { head :no_content }
      format.js
    end
  end

  def add_minimum_price
    @request = Request.find(params[:id])
    params   = add_minimum_price_params
    params['minimum_price'] = params['price']

    respond_to do |format|
      if @request.update_attributes(params) and !params['price'].blank?
        if current_user.role == 'provider'
          @bid = Bid.new
          @bid.user_id    = current_user.id
          @bid.request_id = @request.id
          @bid.price      = params['minimum_price']
          @bid.save
        end
        format.js { render json: {location: request_path(@request)}, status: :created }
      else
        format.js { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def request_params
      params.require(:request).permit(:name,:minimum_price, :section,:price,:closing_time,:delivery_time,:city,:description,:payment_term,:delivery_term,:nds, :category_id, :payment_desc, :file, :temp_key)
    end

    def add_minimum_price_params
      params.require(:request).permit(:price)
    end

end

app/helpers/request_helper.rb
module RequestHelper
end

app/views/requests/_form.html.slim
=semantic_form_for @request ||= Request.new, remote: true, :html => {:class => "exp-search-form",role: :form, 'data-model' => 'request',:'data-type' => 'json', :enctype => "multipart/form-data"} do |f|
  .form-cover
  .col-modal.payment-block style="padding-bottom: 210px"
    =f.input :name,  label: "Наименование"
    =f.input :section,  label: "Раздел", input_html: { data: { load: "request_category" }, id: "request_category" }
    =f.input :category_id, :as => :hidden, input_html: { id: "request_category_id"  }
    =f.input :closing_time,  label: "Дата и время закрытия заявки", as: :datetimepicker

    .modal-list.section-list(data-target="request_category")
      .close-btn
        | x
      .category-block
        .container
          .col-12
            .category-item
              -Category.roots.each do |root|
                h4.category-header #{root.name}
                -root.children.each do |child|
                  div.category-item-heading
                   =child.name
                  div.exp-content
                    ul.choose-cat
                      -child.children.each do |subchild|
                        -leaves = subchild.children
                        -if leaves.to_a.empty?
                          li
                            a href="#" data-category-id="#{subchild.id}"
                              =subchild.name
                        -else
                          li
                            =subchild.name
                            ul.exp-list
                              -leaves.each do |leave|
                                li
                                  a href="#" data-category-id="#{leave.id}"
                                    =leave.name
    .modal-list.city-list(data-target="request_city")
      .close-btn
        | x
      .category-block
        .container
          .col-12
            .category-item
              -City.all.each do |city|
                p
                  a href="@" data-city-id="#{city.id}" #{city.name}


    =f.input :city,  label: "Город поставки", input_html: { data: { load: "request_city" } }
    =f.input :delivery_time,  label: "Дата поставки", as: :datetimepicker, :input_html => { :class => "no-time" }

    =f.input :temp_key, as: "hidden", input_html:{:value => temp_key}

  .col-modal.payment-block
    label for="password"
      | Подробное описание товара или услуги<br>
    =f.text_area :description,  label: "Описание товара услуги", :size => "30x4"
    =f.input :price, label: "Цена"


    h5
      | Условия оплаты
    .payment-block-item
      =f.input :payment_term, :as => :radio, :collection => {Request::PAYMENT_LABELS[0] => Request::PAYMENT_TYPES[0]},:label => false
    .payment-block-item
      =f.input :payment_term, :as => :radio, :collection => {Request::PAYMENT_LABELS[1] => Request::PAYMENT_TYPES[1]},:label => false
    .payment-block-item
      =f.input :payment_term, :as => :radio, :collection => {Request::PAYMENT_LABELS[2] => Request::PAYMENT_TYPES[2]},:label => false, :wrapper_html => { :class => "show-payment-desc" }
    =f.text_area :payment_desc,  label: "Описание улосвий оплаты", :size => "30x4"
    h5
      | Доставка
    .payment-block-item.ship-block-item
      =f.input :delivery_term, :as => :radio, :collection => {"С доставкой" => true},:label => false
    .payment-block-item.ship-block-item
      =f.input :delivery_term, :as => :radio, :collection => {"Без доставки" => false},:label => false
    h5
      | НДС
    .payment-block-item.tax-block-item
      =f.input :nds, :as => :radio, :collection => {"С НДС" => true},:label => false
    .payment-block-item.tax-block-item
      =f.input :nds, :as => :radio, :collection => {"Без НДС" => false},:label => false
  .exp-search-btn-block
    =f.button 'Сохранить', :class =>'modal-btn'
=semantic_form_for Document.new,:url => documents_create_path(temp_key: @temp_key), :html => {:class => "dropzone default-dropzone", :id => "dropzone"}
  input name="file" type="file" multiple=""
  .help-block

div#saved_files style="display: none"
  -if @request
    -@request.documents.each do |document|
      -if ["png","jpg","jpeg"].include? get_extension(document.file_url)
        div.saved_files data-name="#{document.file_url.split('/').pop()}" data-filetype="image" data-id="#{document.id}" data-src="#{document.file_url}" data-filesize="#{document.file.size}"
      -else
        div.saved_files data-name="#{document.file_url.split('/').pop()}" data-filetype="file" data-id="#{document.id}" data-filesize="#{document.file.size}"

app/views/requests/_request.html.slim
=link_to request_path(request), :class => 'request-item-block'
  .container
    .col-4.request-item.request-item-options
      h1 =request.name
      p.open-time
        span Открытие заявки:&nbsp
        span =request.created_at.strftime('%Y.%m.%d %H:%M')
      p.options
        span Варианты оплаты:&nbsp
        span =request.get_payment_term
    .col-4.request-item.request-item-address
      p.close-time
        span Закрытие заявки:&nbsp
        span =request.closing_time.strftime('%Y.%m.%d %H:%M')
      p.city
        span Город:&nbsp
        span =request.city
      p.tax
        span С НДС или без:&nbsp
        span =request.get_nds
    .col-4.request-item.request-item-ship-options
      h1 Заявка №#{request.id}
      - unless request.delivery_time.blank?
        p.open-time
          span Дата поставки:&nbsp
          span =request.delivery_time.strftime('%Y.%m.%d %H:%M')
      p.options
        span Доставка:&nbsp
        span =request.get_delivery_term
      -unless request.price.blank?
        p.price
          | #{request.price}p

app/views/requests/_requests_search.html.slim
=search_form_for @q, url: {:controller => 'requests', :action => controller.action_name}, :html => {:class => "set-request"}  do |f|
  .req-field-block.col-12
    div.req-field
      label for="request-id"
       | Номер заявки <br>
      =f.text_field :id_eq
    div.req-field
      =f.label :name_cont,  "Наименование товара"
      =f.text_field :name_cont

    div.req-field
      =f.label :delivery_time,  "Дата поставки"
      =f.text_field :delivery_time, :class => "datetimepicker no-time"
    div.req-field
      label for="request-open-date"
        | Дата открытия заявки <br>
      =f.text_field :created_at_cont, :class => "datetimepicker", :id => "request-open-date"
    / div.req-field
    /   =f.label :price_lteq,  "Цена"
    /   =f.range_field :price_lteq, :within => 0..100000, step: 0.5, :id => "price_lteq"

    div.req-field
      =f.label :closing_time_eq,  "Дата закрытия заявки"
      =f.text_field :closing_time_eq, :class => "datetimepicker"

    div.req-field
      =f.label :payment_term_eq,  "Варианты оплаты"
      =f.select(:payment_term_eq,  options_for_select(Request::payment_term_options), :id => "request-payment-options", include_blank: true)

    div.req-field
      =f.label :city_cont,  "Город поставки"
      =f.collection_select :city_cont, City.all, :name, :name, {include_blank: true},{:id => "request-city-send"}
    div.req-field
      =f.label :delivery_term_eq,  "Доставка"
      =f.select :delivery_term_eq,  options_for_select([['С доставкой', true], ['Без доставки', false]]), {:prompt => ""},  :selected => params[:q].try(:[], :delivery_term_eq), :id => "request-delivery-options"
    div.req-field
      =f.label :nds_eq,  "НДС"
      =f.select :nds_eq, options_for_select([['С НДС', true], ['Без НДС', false]]), {:prompt => ""}, {:selected => params[:q].try(:[], :nds_eq), id: "request-nds"}
    -if can? :see_details, Request
      div.req-field
        =f.label :status_eq,  "Статус"
        =f.select(:status_eq,  options_for_select(Request::status_options), :id => "request-payment-options", include_blank: true )
      div.req-field
        =f.label :manager_id_eq,  "Менеджер"
        =f.collection_select :manager_id_eq, User.where(:role => 'manager'), :id, :fio_contact, {include_blank: true}

  =f.submit("Поиск", :class => "req-field-btn")

app/views/requests/_solo_request.html.slim
.solo-request
  .container
    .col-4.request-item.request-item-timings
      h1
        =request.name
        -unless request.file.url.blank?
          =link_to request.file.url, :target => "_blank", :title => "Посмотреть вложение"
            =image_tag "screpka.png", :class => 'attach-icon'
      p.open-time
        span Открытие заявки:&nbsp
        span =request.created_at.strftime('%Y.%m.%d %H:%M')
      p.open-time
        span Закрытие заявки:&nbsp
        span =request.closing_time.strftime('%Y.%m.%d %H:%M')
      -unless request.delivery_time == nil
        p.delivery-date
          span Дата поставки:&nbsp
          span =request.delivery_time.strftime('%Y.%m.%d %H:%M')
        p.options
          span Варианты оплаты:&nbsp
          span =request.get_payment_term
      -if can? :see_details,@request
        p.options
          span Отправил:&nbsp
          =link_to profile_path(request.user)
            span =request.user.company_name
        p.options
          span Статус:&nbsp
          -if request.status == 'active' and request.closing_time < Time.current
            span Окончена по времени
          -else
            span =request.get_status
        p.options
          span Менеджер:&nbsp
          -if request.manager
            span =request.manager.fio_contact
          -else
            span Неназначен
    .col-4.request-item.request-solo-item-options
      p.city.request-solo-item-option
        span #{request.city}&nbsp
      p.tax.request-solo-item-option
        span =request.get_nds
      p.delivery.request-solo-item-option
        span =request.get_delivery_term
      p.options
        span Вложения:&nbsp
        -request.documents.each do |document|
          .document-preview
            -if ["png","jpg","jpeg"].include? get_extension(document.file_url)
              =link_to documents_show_path(document), class: 'modal-trigger', data: {target: "image#{document.id}"}
                .document-image
                  =image_tag document.file_url
            -else
              =link_to document.file_url, :target => "_blank"
                .document-image
                  .dz-filename
                    span ОТКРЫТЬ
    .col-4.request-item.request-item-ship-options
      h1 Заявка №#{request.id}
      p.start-price
        span Начальная цена&nbsp
        span.price #{request.price}р
      p.minimal-price
        span Минимальная цена&nbsp
        span.price #{request.minimum_price}р
    .col-12.request-item.request-item-timings
      -if request.payment_term == Request::PAYMENT_TYPES[2]
        p.options
          span Условия оплаты:&nbsp
          span =request.payment_desc
      -unless request.description.blank?
        p.options
          span Описание:&nbsp
          span =request.description
    -if user_signed_in?
      .col-12.add-price-cont
        -if @request.price.blank? && current_user.status == 'active' && current_user.role != 'manager'
            =semantic_form_for @request,url: addMinimumPrice_path(@request),:remote => true, :html => {:id => 'add_minimum_price',role: :form, 'data-model' => 'request', :'data-type' => 'json'} do |f|
              p введите цену:
              li style="display: inline-block; width: 190px"
                input type="text" name="request[price]"
              button.login-btn style="display: vertical-align: bottom" Добавить цену
        -else
          -if can?(:create, Bid) && (@request.bids.last.nil? || @request.bids.last.user_id != current_user.id) && @request.status == 'active' && @request.closing_time > Time.current && current_user.status == 'active' && !@request.price.blank?
            =semantic_form_for Bid.new, :remote => true, :html => {:id => 'new_bid',role: :form, 'data-model' => 'bid'} do |f|

                =f.input :request_id, :as => :hidden, :input_html => { :value => @request.id }
                button.login-btn Цена -1%
        -if can? :destroy, @request
          =link_to request_path(@request), :method => :delete
            button.registr-btn Удалить
        -if can? :take, @request
          =link_to request_take_path(@request)
            button.add-btn Взять заявку
        -if can? :refused, @request
          =link_to request_refused_path(@request)
            button.registr-btn Отказ от оплаты
        -if (can?(:close, @request)) && (@request.closing_time < Time.current)
          =link_to request_close_path(@request)
            button.registr-btn Закрыть заявку
        -if can? :payed, @request
          =link_to request_payed_path(@request)
            button.login-btn Счет оплачен
        -if can? :update, @request
          =link_to edit_request_path, class: 'modal-trigger', data: {target: 'add-bid'}
            button.add-btn Редактировать заявку

app/views/requests/index.html.slim
== render 'partials/header'
.set-container
  .container
    =render 'requests/requests_search'


=render @requests
.pagination-cont
  =paginate @requests

== render 'partials/footer'

app/views/requests/show.html.slim
== render 'partials/header'
=  render 'requests/solo_request', :request => @request
.bids-cont
  -reset_id()
  =render @request.bids, :request => @request
.closed-cont
  -if @request.closing_time < Time.current and user_signed_in? and (@request.status != Request::STATUS_TYPES[3] or @request.status != Request::STATUS_TYPES[4])
    -if current_user.id == @request.user_id
      h1 Время заявки истелко. Ожидайте, с вами свяжется менеджер
    -elsif current_user.role == 'provider' or current_user.role == 'client'
      h1 Время заявки истелко.
.container
  =link_to 'Перейти к списку заявок', requests_path, :class => 'to-all-req'


== render 'partials/footer'

app/views/requests/take.js.erb
$('#take-request').remove()