config/routes.rb
  Rails.application.routes.draw do

  root 'main#index'
  ActiveAdmin.routes(self)

  get 'categories/import', to: 'categories#import'
  get 'categories/import_city', to: 'categories#import_city'
  get 'categories/:id', to: 'categories#index', as: 'categories'

  get 'contact', to: 'pages#contact', as: 'contact'
  get 'rules',   to: 'pages#rules',   as: 'rules'
  get 'about',   to: 'pages#about',   as: 'about'
  get 'dogovor', to: 'pages#dogovor', as: 'dogovor'
  get 'news',    to: 'pages#news',    as: 'news'

  get 'profile(/:id)', to: 'users#index', as: 'profile'
  get 'users/login'
  get 'users/reg'
  get 'users/new_password'
  get 'profile/requests(/:type/(:id))', to: 'users#requests', as: 'profile_requests'
  get 'profile/bids(/:type/(:id))',       to: 'users#bids', as: 'profile_bids'
  get 'profile/managed(/:type(:id/))',     to: 'users#managed', as: 'profile_managed'

  patch 'requests/addMinimumPrice/:id', to: 'requests#add_minimum_price', as: 'addMinimumPrice'
  get   'requests/searchModal', to: 'requests#search_modal', as: 'search_modal'
  get   'requests/cat:id', to: 'requests#index', as: 'requests_category'
  get   'requests/archive', to: 'requests#archive', as: 'requests_archive'
  get   'requests/await', to: 'requests#await', as: 'requests_await'
  get   'requests/refused/:id', to: 'requests#refused', as: 'request_refused'
  get   'requests/payed/:id', to: 'requests#payed', as: 'request_payed'
  get   'requests/close/:id', to: 'requests#close', as: 'request_close'
  get   'requests/take/:id', to: 'requests#take', as: 'request_take'

  get  'invoice/:id', to: 'invoice#show', as: 'invoice'
  get  'bill/:id', to: 'invoice#bill', as: 'bill'

  resources :contacts,
    :controller => 'contacts',
    :only       => [:create]

  post '/documents/:temp_key', to: 'documents#create', as: 'documents_create'
  get '/documents/:id', to: 'documents#show', as: 'documents_show'
  delete '/documents/:id', to: 'documents#delete', as: 'documents_delete'
  resources :requests
  resources :bids, :only => [:create]

  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations', passwords: 'passwords'}
  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_nested_set
  has_many :requests

  # def self.import(file)
  #   CSV.foreach(file, headers: true) do |row|
  #   category = where(id: row["id"])
  #     .first_or_create!(row.to_hash)
  #   end
  # end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @category = Category.find(params[:id])
  end

  # def import
  #   Category.import("#{Rails.root}/public/categories.csv")
  #   redirect_to root_url, notice: "Products imported."
  # end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.slim
.col-3.main-col
      h2
        =category.name
      ul
        -category.children.each do |child|
          li
            a(href="#{categories_path(child)}")
              =child.name

app/views/categories/_internal_category.html.slim
-categories.each do |cat|
  .category-item.col-12
    -leaves = cat.children
    -if leaves.to_a.empty?
      div.category-item-heading
       =link_to requests_category_path(cat)
         =cat.name

    -else
      div.category-item-heading =cat.name
      div.exp-content
        ul
          -leaves.each do |cat|
            li
              =link_to requests_category_path(cat)
                | - #{cat.name}

app/views/categories/index.html.slim
== render 'partials/header'
.breadcrumbs
  .container
    ul
      li
        a href="#"
          = @category.root.name
      li
        a href="#"
          = @category.name
.category-block
  .container
    .main-heading
      h1 = @category.name
    .col-12
      =render 'categories/internal_category', :categories => @category.children




== render 'partials/footer'